#-------------------------------------------------------------------------------
# Copyright (C) 2017 ATOS.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     ATOS - initial API and implementation
#-------------------------------------------------------------------------------
mongo:
   image: mongo:3.2
   command: --nojournal
orion:
   image: fiware/orion
   links:
     - mongo
   ports:
     - "1026:1026"
   command: -dbhost mongo
rabbitmq:
   image: rabbitmq:3.6
   hostname: my-rabbit
   ports:
     - "15672:15672"
     - "5672:5672"
mosquitto:
   image: toke/mosquitto
   ports:
     - "1883:1883"
     - "9001:9001"
idas:
   image: telefonicaiot/iotagent-ul
   links:
     - orion
     - mosquitto
     - mongo
   ports:
     - "7896:7896"
     - "4041:4041"
